[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-ta.*]
ignore_missing_imports = True

[mypy-shap.*]
ignore_missing_imports = True

[mypy-xgboost.*]
ignore_missing_imports = True